apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fourest-ingress
  namespace: fourest
  labels:
    app: fourest
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    # Akceptuje localhost (dla macOS) i fourest.local (dla Linux)
    - http:
        paths:
          # 1. Ścieżka dla API - przekazuje /api/* jako /api/* do backendu
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000

          # 2. Ścieżka dla Frontendu (domyślna)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
